---
abstract: unknown
author:
  - unknown
build_requires:
  Inline::C: 0
  Inline::Filters::Ragel: 0
  Inline::Module: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Truncate
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/hoytech/Unicode-Truncate/issues
  repository: git://github.com/hoytech/Unicode-Truncate.git
version: 0.100
